// PDF: overwrite in place, never resize.
//
// A PDF's cross-reference table is a list of byte offsets into the file. Delete
// four bytes anywhere before it and every offset after that point is wrong, and
// the document is broken. Rebuilding the xref means implementing a PDF writer,
// which is a real library and not something to carry into a page that has to
// stay dependency-free.
//
// So metadata values are blanked *in place*: the same bytes, filled with
// spaces. The offsets never move, the file stays valid, and nothing readable
// remains. This is the "degraded but honest" path — see `cleanPdf`'s object
// stream warning for what it cannot reach.

import type { Finding } from '../report.ts'
import { snippet, startsWith, type ContainerResult } from './types.ts'

export const sniffPdf = (bytes: Uint8Array) => startsWith(bytes, [0x25, 0x50, 0x44, 0x46]) // %PDF

/** Byte-for-char view, so a regex index is a byte offset. */
function latin1(bytes: Uint8Array): string {
  let out = ''
  const chunk = 8192
  for (let i = 0; i < bytes.length; i += chunk) {
    out += String.fromCharCode(...bytes.subarray(i, i + chunk))
  }
  return out
}

const INFO_KEYS = [
  'Producer',
  'Creator',
  'Author',
  'Title',
  'Subject',
  'Keywords',
  'CreationDate',
  'ModDate',
]

/** Decode a PDF hex string, `<48656C6C6F>`, for reporting. */
function fromHex(body: string): string {
  const digits = body.replaceAll(/[^0-9A-Fa-f]/g, '')
  let out = ''
  for (let i = 0; i + 1 < digits.length; i += 2) {
    out += String.fromCharCode(Number.parseInt(digits.slice(i, i + 2), 16))
  }
  return out
}

export function cleanPdf(bytes: Uint8Array): ContainerResult {
  const text = latin1(bytes)
  const output = bytes.slice()
  const findings: Finding[] = []

  const blank = (start: number, end: number) => output.fill(0x20, start, end)

  // 1. Document information dictionary entries.
  for (const key of INFO_KEYS) {
    const pattern = new RegExp(
      String.raw`/${key}\s*(?:\(((?:[^()\\]|\\.)*)\)|<([0-9A-Fa-f\s]*)>)`,
      'g',
    )
    for (const match of text.matchAll(pattern)) {
      const [whole, literal, hex] = match
      const value = literal ?? (hex === undefined ? '' : fromHex(hex))
      if (!value.trim()) continue

      // Blank the value only, leaving the delimiters so the syntax stays legal.
      const valueStart = match.index + whole.indexOf(literal === undefined ? '<' : '(') + 1
      blank(valueStart, valueStart + (literal ?? hex ?? '').length)

      findings.push({
        kind: 'doc_property',
        verdict: 'informational',
        offset: match.index,
        length: whole.length,
        label: `/${key} in the document information dictionary`,
        evidence: snippet(value),
      })
    }
  }

  // 2. XMP packets, which is where "generated by" claims usually live. The
  //    packet has trailing padding by design, so filling it with spaces leaves
  //    a well-formed, empty packet rather than a hole.
  const packet = /<\?xpacket begin=[\s\S]*?<\?xpacket end=[^?]*\?>/g
  for (const match of text.matchAll(packet)) {
    const tool = /<(?:xmp:CreatorTool|pdf:Producer|dc:creator)>([^<]*)</.exec(match[0])?.[1]
    blank(match.index, match.index + match[0].length)
    findings.push({
      kind: 'xmp',
      verdict: 'probable',
      offset: match.index,
      length: match[0].length,
      label: 'XMP metadata packet',
      ...(tool ? { evidence: snippet(tool) } : {}),
    })
  }

  // 3. Say what could not be reached, rather than implying the file is clean.
  //    PDF 1.5 can pack the information dictionary into a compressed object
  //    stream, where it is deflated and invisible to a byte scan.
  if (/\/Type\s*\/ObjStm/.test(text)) {
    findings.push({
      kind: 'doc_property',
      verdict: 'informational',
      offset: 0,
      length: 0,
      label: 'Compressed object streams present — metadata inside them was not reached',
      evidence:
        'This PDF stores objects in compressed streams. Blanking bytes in place cannot see ' +
        'inside them, so metadata may remain. Re-saving the file from a PDF editor rewrites ' +
        'those streams.',
    })
  }

  return { output, findings, preserved: [] }
}
