// PNG: a signature followed by length-prefixed chunks.
//
// Removing a chunk is the whole operation. Every chunk carries its own CRC over
// its own bytes, so dropping one leaves the others valid — no recompression, no
// re-encoding, and the pixels come out byte-identical to what went in. That
// property is worth protecting: a "metadata cleaner" that silently re-encodes
// an image has changed the thing the user was trying to preserve.

import type { Finding, FindingKind, Verdict } from '../report.ts'
import {
  ascii,
  concat,
  decodeUtf8,
  readU32,
  snippet,
  startsWith,
  type ContainerResult,
} from './types.ts'

const SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]

export const sniffPng = (bytes: Uint8Array) => startsWith(bytes, SIGNATURE)

interface ChunkRule {
  kind: FindingKind
  verdict: Verdict
  what: string
}

// iCCP is deliberately absent: a colour profile is not provenance, and dropping
// it changes how the image renders. Same for pHYs, gAMA and the rest of the
// rendering chunks.
const RULES: Record<string, ChunkRule> = {
  tEXt: { kind: 'text_chunk', verdict: 'informational', what: 'uncompressed text chunk' },
  zTXt: { kind: 'text_chunk', verdict: 'informational', what: 'compressed text chunk' },
  iTXt: { kind: 'text_chunk', verdict: 'informational', what: 'international text chunk' },
  eXIf: { kind: 'exif', verdict: 'informational', what: 'EXIF block' },
  // C2PA stores its signed manifest in a private chunk. Its presence is not
  // ambiguous: something deliberately stamped this file with its origin.
  caBX: { kind: 'c2pa', verdict: 'confirmed', what: 'C2PA provenance manifest' },
  dSIG: { kind: 'c2pa', verdict: 'confirmed', what: 'digital signature chunk' },
}

/** Read the keyword a text chunk is filed under, and enough of its value to show. */
function describeText(type: string, data: Uint8Array): { keyword: string; value: string } {
  const nul = data.indexOf(0)
  const keyword = nul === -1 ? '' : decodeUtf8(data.subarray(0, nul))

  // zTXt and iTXt values may be deflated. Reporting the keyword is enough to
  // tell the user what is there; decompressing to quote it is not worth
  // carrying a decompressor into the report path.
  if (type === 'tEXt' && nul !== -1) {
    return { keyword, value: snippet(decodeUtf8(data.subarray(nul + 1))) }
  }
  return { keyword, value: '' }
}

export function cleanPng(bytes: Uint8Array): ContainerResult {
  const findings: Finding[] = []
  const kept: Uint8Array[] = [bytes.subarray(0, SIGNATURE.length)]

  let offset = SIGNATURE.length
  while (offset + 8 <= bytes.length) {
    const length = readU32(bytes, offset)
    const type = ascii(bytes, offset + 4, 4)
    const total = 12 + length // length + type + data + crc
    if (total <= 0 || offset + total > bytes.length) break

    const rule = RULES[type]
    if (rule) {
      const data = bytes.subarray(offset + 8, offset + 8 + length)
      const { keyword, value } = describeText(type, data)
      // XMP arrives as an iTXt chunk under a specific keyword, and it is where
      // "generated by" claims usually live, so it is worth naming precisely.
      const isXmp = keyword === 'XML:com.adobe.xmp'

      findings.push({
        kind: isXmp ? 'xmp' : rule.kind,
        verdict: isXmp ? 'probable' : rule.verdict,
        offset,
        length: total,
        label: `${type} — ${isXmp ? 'XMP packet' : rule.what}${keyword ? ` (${keyword})` : ''}`,
        ...(value ? { evidence: value } : {}),
      })
    } else {
      kept.push(bytes.subarray(offset, offset + total))
    }

    offset += total
    if (type === 'IEND') break
  }

  return { output: concat(kept), findings, preserved: [] }
}
