// GENERATED by scripts/eval-authorship.mjs --fit. Do not edit by hand:
// rerun the evaluation, which rewrites this file and the report beside it.
//
// Every report carries this id, so a verdict can always be traced to the
// weights and thresholds behind it, and those to the corpus they were fitted on.

export interface Calibration {
  /** Named in every report. */
  id: string
  /** False until weights and thresholds were fitted on a labelled corpus. */
  calibrated: boolean
  /** When the fit ran, ISO date. */
  date: string | null
  /** Which corpus it ran on, by manifest hash. */
  corpus: string | null
  weights: {
    spans: number
    lexicon: number
    discourse: number
    variation: number
    stylometry: number
    forensic: number
  }
  thresholds: { human: number; ai: number }
}

export const CALIBRATION: Calibration = {
  id: 'fit-2026-09-30-ba0e67364077-a56b9f',
  calibrated: true,
  date: '2026-09-30',
  corpus: 'ba0e67364077',
  weights: {
    spans: 0,
    lexicon: 0.41,
    discourse: 0.053,
    variation: 0.298,
    stylometry: 0.139,
    forensic: 0.1,
  },
  thresholds: {
    human: 0.05,
    ai: 0.5,
  },
}
