// GENERATED by scripts/eval-authorship.mjs --fit. Do not edit by hand:
// rerun the evaluation, which rewrites this file and the report beside it.
//
// `provisional-0` is the hand-set starting point, before any fit. Every report
// carries this id, so a verdict can always be traced to the weights behind it.

export interface Calibration {
  /** Named in every report. */
  id: string
  /** False until weights and thresholds were fitted on a labelled corpus. */
  calibrated: boolean
  /** When the fit ran, ISO date. */
  date: string | null
  /** Which corpus it ran on, by manifest hash. */
  corpus: string | null
  weights: {
    spans: number
    lexicon: number
    discourse: number
    stylometry: number
    forensic: number
  }
  thresholds: { human: number; ai: number }
}

export const CALIBRATION: Calibration = {
  id: 'provisional-0',
  calibrated: false,
  date: null,
  corpus: null,
  weights: { spans: 0.2, lexicon: 0.25, discourse: 0.25, stylometry: 0.2, forensic: 0.1 },
  thresholds: { human: 0.3, ai: 0.7 },
}
