// English words and phrases that turn up far more often in generated prose.
//
// One list, read by two consumers: stylometry counts them per thousand words,
// and the authorship catalogue locates them sentence by sentence. Keeping them
// here is what stops the two from drifting into different ideas of what
// "marker vocabulary" means.
//
// Lowercase. Phrases are matched with their spaces, case-insensitively.

export const MARKERS: readonly string[] = [
  'delve',
  'delving',
  'tapestry',
  'testament to',
  'realm of',
  'underscore',
  'underscores',
  'pivotal',
  'crucial',
  'leverage',
  'leveraging',
  'robust',
  'seamless',
  'seamlessly',
  'intricate',
  'nuanced',
  'multifaceted',
  'landscape',
  'navigating',
  'foster',
  'fostering',
  'unlock',
  'elevate',
  'embark',
  'myriad',
  'plethora',
  'paradigm',
  'holistic',
  'synergy',
  'cutting-edge',
  'game-changer',
  'deep dive',
  'resonate',
  'showcase',
  'spearhead',
  'meticulous',
  'meticulously',
  'boasts',
  'vibrant',
  'bustling',
  'treasure trove',
  "in today's",
  'fast-paced',
  'ever-evolving',
  "it's worth noting",
  "it's important to note",
  'that said',
  'moreover',
  'furthermore',
]

/** unslop's business-jargon triggers: the register, rather than the vocabulary. */
export const JARGON: readonly string[] = [
  'navigate challenges',
  'leverage synergies',
  'circle back',
  'move the needle',
  'low-hanging fruit',
  'actionable insights',
  'drive value',
  'unlock potential',
  'best practices',
  'thought leadership',
  'value proposition',
  'core competency',
  'double down',
  'north star',
  'boil the ocean',
  'table stakes',
]
